### ISSUE TITLE
Different branches for different channels

### ISSUE THREAD

**Issue by JJGadgets** [flathub/com.microsoft.Edge#40]
Could you perhaps have different branches or different packages for the different channels of Edge (Beta, Dev, and Stable & Canary when they release)? I'd like to run Dev as I do on my macOS & Windows systems for familiarity but it seems that the Beta branch is now used.

**Comment by TheEvilSkeleton** [comment]
I talked about it before and I have formed my conclusion, see https://github.com/flathub/com.microsoft.Edge/issues/37#issuecomment-832744327.

I would also add that I have recently contacted Microsoft but I have not received any response from them. I already maintain more than 7 Flatpak packages and maintaining another one will become a burden for me since I am on the lookout for a job.

I would appreciate it if you could contact Microsoft as well. It is difficult to get the attention of a company when it is a one-man army.

**Comment by JJGadgets** [comment]
I see, sorry for not checking around.
