### ISSUE TITLE
Does not integrate with `ms-edgedevtools.vscode-edge-devtools`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [flathub/com.microsoft.Edge#448]
https://github.com/microsoft/vscode-edge-devtools/issues/1984#issue-2110796586

**Comment by evan-a-a** [comment]
The flatpak application structure hasn't really changed recently. I think this is probably a configuration thing on the vscode extension side.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/com.microsoft.Edge/issues/448#issuecomment-1939774673

@evan-a-a, what does that entail specifically - that you believe that this issue has been caused upstream, perhaps? That would seem incredibly strange to me, considering that this project *repackages* VSCode in its *designed* form into a form which is officially unsupported. I hope I have misconstrued what you have stated.

**Comment by evan-a-a** [comment]
This repo is for repackaged Microsoft Edge. Did you mean to file this against the VSCode package? I would not expect the VSCode edge developer extension to work with the Flatpak'ed Microsoft Edge due to the nature of flatpaks, and I would be very surprised to know that it ever worked.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/com.microsoft.Edge/issues/448#issuecomment-1941917751

Hence the issue, @evan-a-a.

**Comment by evan-a-a** [comment]
There's not really anything we can do about this because of the limitations of Flatpaks. In this case, we're packaging a proprietary application in a way that it was not designed to be. The extension for VSCode expects Edge to be installed via traditional methods. Now if the extension were modified to work with the flatpak and that wasn't working, it'd be a different story. 

I'm going to close this issue as I don't think there's anything actionable here.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/com.microsoft.Edge/issues/448#issuecomment-1952941976

@evan-a-a, https://github.com/microsoft/vscode-edge-devtools/issues/1984#issuecomment-1952947191.
