### ISSUE TITLE
How to get controllers to be detected by Edge

### ISSUE THREAD

**Issue by okseb** [flathub/com.microsoft.Edge#81]
I checked the perms with Flatseal and I don't see anything that should be blocking it from being detected but I tested with [https://gamepad-tester.com/](https://gamepad-tester.com/) vs natively installed Firefox and it doesn't detect in Flatpak Edge or Chromium.

Edit: I tried Firefox Flatpak to verify apples to apples just Flatpak vs native and still nothing.

**Comment by rowbawts** [comment]
> I haven't really used a controller so I don't really know how to get it working. Could you take a look at https://github.com/flathub/com.valvesoftware.Steam/wiki#my-controller-isnt-being-detected and let me know whether it works or not?

I fully understand however my controller actually works with the Steam Flatpak as well lol.

**Comment by tinywrkb** [comment]
Look [here](https://github.com/flathub/org.chromium.Chromium/issues/40), read the comment about mounting `/run/udev`. I'm not sure if it's need, but you might want to confirm that the sandbox has access to `/dev/bus/usb`.

**Comment by rowbawts** [comment]
> I'm gonna be honest, I don't know.

It's fine because if I knew either I'd just contribute, but if the comment refi made in that referenced issue is true then that's yet another area where Flatpak is not developed enough, because to my mind a portal for devices is huge to achieve the same experience as native apps.

Side note, issues like these really suck because I use Silverblue an OS pretty much designed to use Flatpak exclusively and I love the idea of it but I have to limit myself to all these compromises to do so and in the end I feel like it just hurts it's image among most users when they try it and run into all these problems and that damages its adaptability. /endrant

**Comment by TheEvilSkeleton** [comment]
I lack knowledge on this so I'm going to ask in the Flatpak Matrix and see what they have to say.
